#ifndef VERSION_H
#define VERSION_H

#ifndef VERSION_STR_POSTFIX
#ifdef CFG_INTERFACE
#define VERSION_STR_POSTFIX "_fullmac"
#else
#define VERSION_STR_POSTFIX ""
#endif
#endif /* VERSION_STR_POSTFIX */

#ifndef GIT_VERSION_STR_POSTFIX
#define GIT_VERSION_STR_POSTFIX ""
#endif /* GIT_VERSION_STR_POSTFIX */

#define VERSION_STR "2.10" VERSION_STR_POSTFIX GIT_VERSION_STR_POSTFIX

#endif /* VERSION_H */
